# Copyright 2023-2025 Hugo Osvaldo Barrera
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "pimsync"
edition = "2021"
description = "Synchronize calendars and contacts"
homepage = "https://pimsync.whynothugo.nl/"
license = "EUPL-1.2"
build = "build.rs"

[profile.release]
lto = true

[dependencies]
anyhow = "1.0.75"
base64 = "0.22.1"
camino = { version = "1.1.6" }
futures-util = "0.3.31"
hex = "0.4.3"
hyper = { version = "1", features = ["http1", "client"] }
hyper-rustls = "0.26.0"
hyper-util = { version = "0.1.1", features = ["client", "client-legacy", "http1"] }
hyperlocal = "0.9.1"
lexopt = "0.3.0"
libdav = { version = "0.9.3" }
log = "0.4.20"
rustix = { version = "0.38.10", features = ["fs"] }
rustls = { version = "0.22.4" }
rustls-pemfile = "2.0.0"
scfg = "0.3.1"
sha2 = "0.10.2"
simple_logger = { version = "4.1.0", default-features = false, features = ["colors", "stderr"] }
tempfile = "3.3.0"
thiserror = "1.0.37"
tokio = { version = "1.33.0", features = ["rt-multi-thread", "macros", "rt"] }
tower = "0.5.1"
vstorage = { version = "0.1.0" }
