# Copyright 2023-2025 Hugo Osvaldo Barrera
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "pimsync"
edition = "2024"
description = "Synchronize calendars and contacts"
homepage = "https://pimsync.whynothugo.nl/"
repository = "https://git.sr.ht/~whynothugo/pimsync"
license = "EUPL-1.2"
build = "build.rs"
rust-version = "1.86.0"

[profile.release]
lto = true

[features]
default = ["jmap"]
jmap = ["vstorage/jmap"]

[dependencies]
anyhow = "1.0.75"
base64 = "0.22"
camino = { version = "1.1.6" }
futures-util = "0.3.31"
hex = "0.4.3"
hyper = { version = "1", features = ["http1", "client"] }
hyper-rustls = { version = "0.27.0", default-features = false, features = ["ring", "http1", "native-tokio", "tls12", "rustls-native-certs"] }
hyper-util = { version = "0.1.1", features = ["client", "client-legacy", "http1"] }
hyperlocal = "0.9.1"
lexopt = "0.3.0"
log = "0.4.20"
rustix = { version = "1", features = ["fs"] }
rustls = { version = "0.23.4", default-features = false, features = ["logging", "ring", "tls12"]}
rustls-pemfile = "2.0.0"
scfg = "0.3.1"
sha2 = "0.10.2"
simple_logger = { version = "5", default-features = false, features = ["colors", "stderr"] }
tempfile = "3.3.0"
thiserror = "2"
tokio = { version = "1.33.0", features = ["rt-multi-thread", "macros", "rt"] }
tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.6.6", default-features = false, features = ["auth", "set-header"] }
vstorage = { version = "0.4.0", default-features = false }
