# Copyright 2023-2025 Hugo Osvaldo Barrera
#
# SPDX-License-Identifier: EUPL-1.2

image: alpine/edge
packages:
  - cargo
  - cargo-audit
  - cargo-deny
  - mandoc
  - py3-sphinx
  - rsync
  - rust
  - rust-clippy
  - rustfmt
  - scdoc
environment:
  ANCHOR_PUB_KEY: AAAAC3NzaC1lZDI1NTE5AAAAIE2WacYpYEP5vvevx4NXQn3Ktd53pBkZR/bpPoS3Wkyg
  CARGO_TERM_COLOR: always
sources:
  - https://git.sr.ht/~whynothugo/pimsync
triggers:
  - action: email
    condition: failure
    to: Hugo Osvaldo Barrera <hugo@whynothugo.nl>
secrets:
  - 2d3090e6-72a6-4d00-8221-92184d276c90 # rsync@anchor
tasks:
  - prepare: |
      cd pimsync
      cargo fetch --locked  # make sure lockfile is up to date
  - check: |
      cd pimsync
      make check
  - docs: |
      cd pimsync
      make docs
  - audit: |
      cd pimsync
      cargo-audit audit
  - main-or-tag: |
      cd pimsync
      git diff --no-patch --exit-code origin/main || git describe --tag --exact-match || complete-build
  - publish-doc: |
      cd pimsync
      echo "anchor.whynothugo.nl ssh-ed25519 $ANCHOR_PUB_KEY" > $HOME/.ssh/known_hosts
      if git diff --no-patch --exit-code origin/main; then
        DIR=.
      else
        DIR=$(git describe --tag --exact-match)
      fi
      rsync -r docs/build/html/ rsync@anchor.whynothugo.nl:./$DIR
