# Copyright 2024-2025 Hugo Osvaldo Barrera
#
# SPDX-License-Identifier: EUPL-1.2

image: openbsd/7.7
packages:
  - rust
  - rust-rustfmt
  - rust-clippy
sources:
  - https://git.sr.ht/~whynothugo/pimsync
  - https://git.sr.ht/~whynothugo/vstorage
  - https://git.sr.ht/~whynothugo/libdav
environment:
  CARGO_TERM_COLOR: always
triggers:
  - action: email
    condition: failure
    to: Hugo Osvaldo Barrera <hugo@whynothugo.nl>
tasks:
  - prepare: |
      cd pimsync
      cargo fetch --locked  # make sure lockfile is up to date
  - no-cargo-deny: |
      # cargo-deny is not packaged on OpenBSD
      sed -i /cargo-deny/d pimsync/Makefile
  - check: |
      cd pimsync
      make check
