# Copyright 2023 Hugo Osvaldo Barrera
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "vdirsyncer"
version = "0.0.1"
edition = "2021"
description = "Synchronize calendars and contacts"
homepage = "https://github.com/pimutils/vdirsyncer/issues/946"
license = "EUPL-1.2"

[dependencies]
anyhow = "1.0.75"
serde = { version = "1.0.188", features = ["derive"] }
toml = { version = "0.8.1", features = ["parse"], default-features = false }
vstorage = { version = "0.1.0", path = "../vstorage" }
