# Copyright 2023 Hugo Osvaldo Barrera
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "vdirsyncer"
version = "0.0.1"
edition = "2021"
description = "Synchronize calendars and contacts"
homepage = "https://github.com/pimutils/vdirsyncer/issues/946"
license = "EUPL-1.2"

[dependencies]
anyhow = "1.0.75"
camino = { version = "1.1.6", features = ["serde1"] }
clap = { version = "4.0.0", features = ["derive"] }
hyper = "0.14.27"
hyper-rustls = "0.25.0"
libdav = { version = "0.2.0", path = "../libdav" }
log = "0.4.20"
rustls = { version = "0.22.1" }
rustls-pemfile = "2.0.0"
serde = { version = "1.0.188", features = ["derive"] }
sha2 = "0.10.2"
simple_logger = { version = "4.1.0", default-features = false, features = ["colors"] }
tokio = { version = "1.33.0", features = ["macros", "rt"] }
toml = { version = "0.8.1", features = ["parse"], default-features = false }
vstorage = { version = "0.1.0", path = "../vstorage" }
