# Copyright 2023-2024 Hugo Osvaldo Barrera
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "vdirsyncer"
version = "0.0.1"
edition = "2021"
description = "Synchronize calendars and contacts"
homepage = "https://github.com/pimutils/vdirsyncer/issues/946"
license = "EUPL-1.2"

[dependencies]
anyhow = "1.0.75"
camino = { version = "1.1.6", features = ["serde1"] }
hyper = "0.14.27"
hyper-rustls = "0.25.0"
lexopt = "0.3.0"
libdav = { version = "0.3.0", path = "../libdav" }
log = "0.4.20"
rustix = { version = "0.38.10", features = ["fs"] }
rustls = { version = "0.22.4" }
rustls-pemfile = "2.0.0"
serde = { version = "1.0.188", features = ["derive"] }
sha2 = "0.10.2"
simple_logger = { version = "4.1.0", default-features = false, features = ["colors"] }
tempfile = "3.3.0"
tokio = { version = "1.33.0", features = ["rt-multi-thread", "macros", "rt"] }
toml = { version = "0.8.1", features = ["parse"], default-features = false }
vstorage = { version = "0.1.0", path = "../vstorage" }
