# Copyright 2023 Hugo Osvaldo Barrera
#
# SPDX-License-Identifier: EUPL-1.2

[build]
rustdocflags = ["--deny=warnings", "--allow=incomplete-features"]

# Uncomment these when developing all crates locally.
#[patch.crates-io]
#vstorage = { path = "./vstorage" }
