# Copyright 2023 Hugo Osvaldo Barrera
#
# SPDX-License-Identifier: EUPL-1.2

[build]
rustdocflags = ["--deny=warnings", "--allow=incomplete-features"]

[patch.crates-io]
libdav = { path = "../libdav" }
libjmap = { path = "../libjmap" }
vstorage = { path = "../vstorage" }
