# Copyright 2024 Hugo Osvaldo Barrera
#
# SPDX-License-Identifier: EUPL-1.2

image: openbsd/7.5
packages:
  - rust
  - rust-rustfmt
  - rust-clippy
sources:
  - https://git.sr.ht/~whynothugo/pimsync
environment:
  CARGO_TERM_COLOR: always
triggers:
  - action: email
    condition: failure
    to: Hugo Osvaldo Barrera <hugo@whynothugo.nl>
tasks:
  - prepare: |
      cd pimsync
      cargo fetch --locked  # make sure lockfile is up to date
  - build: |
      cd pimsync
      cargo build
  - lint: |
      cd pimsync
      cargo fmt --check
      cargo clippy
  - test: |
      cd pimsync
      cargo test  # includes examples and doctests
  - doc: |
      cd pimsync
      cargo doc  # fails on broken links
