# Copyright 2023-2024 Hugo Osvaldo Barrera
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "vstorage"
version = "0.1.0"
authors = ["Hugo Osvaldo Barrera <hugo@whynothugo.nl>"]
edition = "2021"
description = "A common API for various icalendar/vcard storages."
readme = "README.md"
homepage = "https://github.com/pimutils/vdirsyncer/issues/946"
keywords = ["vdir", "filesystem", "icalendar", "caldav"]
license = "EUPL-1.2"

[dependencies]
async-trait = "0.1.64"
camino = { version = "1.1.6" }
http = "0.2.9"
hyper = "0.14.24"
hyper-rustls = "0.25.0"
libdav = { version = "0.2.0", path = "../libdav" }
log = "0.4.17"
sha2 = "0.10.2"
sqlite = "0.32.0"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["io-util", "fs"] }
vparser = "1.0.0"

[dev-dependencies]
anyhow = "1.0.71"
rand = "0.8.5"
tempfile = "3.3.0"
tokio = { version = "1.21.2", features = ["full"] }
