# Copyright 2023-2024 Hugo Osvaldo Barrera
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "vstorage"
version = "0.1.0"
authors = ["Hugo Osvaldo Barrera <hugo@whynothugo.nl>"]
edition = "2021"
description = "A common API for various icalendar/vcard storages."
readme = "README.md"
homepage = "https://sr.ht/~whynothugo/vdirsyncer-rs/"
keywords = ["vdir", "filesystem", "icalendar", "caldav"]
license = "EUPL-1.2"

[dependencies]
async-trait = "0.1.64"
camino = { version = "1.1.6" }
futures-util = "0.3.28"
http = "1"
http-body-util = "0.1.0"
hyper = { version = "1", features = ["http1", "client"] }
hyper-rustls = "0.26.0"
hyper-util = { version = "0.1.1", features = ["client", "client-legacy", "http1"] }
libdav = { version = "0.9.0" }
log = "0.4.17"
rand = "0.8.5"
rustix = { version = "0.38.10", features = ["fs"] }
sha2 = "0.10.2"
sqlite = "0.32.0"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["io-util", "fs"] }
tower = "0.5.1"
vparser = "1.0.1"

[target.'cfg(target_os = "linux")'.dependencies]
inotify = "0.11.0"

[dev-dependencies]
anyhow = "1.0.71"
tempfile = "3.3.0"
tokio = { version = "1.21.2", features = ["full"] }
tower-http = { version = "0.6.2", features = ["auth"] }
