baseURL = 'https://vdirsyncer.pimutils.org/'
languageCode = 'en-gb'
title = 'vdirsyncer 2.x documentation'

# From: https://github.com/alex-shpak/hugo-book
theme = "hugo-book"

[params]
  BookTheme = 'auto'
  # We have a hack to render the right-side Toc inside the left-side ToC.
  BookToC = true
