name: Build Debian Package
on:
  push:
    branches:
      - '**'
      - '!main'
      - '!master'
  workflow_dispatch:
    inputs:
      publish:
        description: 'Push the deb to Gemfury?'
        type: boolean
        default: false

jobs:
  build-and-pkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Binary
        run: cargo build --release -p pimsync

      - name: install nfpm
        run: |
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt update
          sudo apt install nfpm

      - name: Generate .deb
        id: package
        run: |
          VERSION=$(git describe --tags --always | sed 's/^v//')
          echo "PKG_VERSION=$VERSION" >> $GITHUB_OUTPUT
          export VERSION
          nfpm package --config nfpm.yaml --target ./pimsync-$VERSION.deb

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: "pimsync-${{ steps.package.outputs.PKG_VERSION }}.deb"
          path: "./pimsync-${{ steps.package.outputs.PKG_VERSION }}.deb"

      - name: Push to Gemfury
        if: github.event.inputs.publish == 'true'
        env:
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
        run: |
          curl -F package=@./pimsync-${{ steps.package.outputs.PKG_VERSION }}.deb https://$FURY_TOKEN@push.fury.io/retorquere/
